"""Direct Python bindings for Rust request, rendering, image, and response components."""

from ._native import (
    ASSISTANT_SP_TOKEN,
    BOS_TOKEN,
    DSML_SP_TOKEN,
    EOS_TOKEN,
    IMAGE_SPECIAL_TOKEN,
    IMAGE_SPECIAL_TOKEN_ID,
    LATEST_REMINDER_SP_TOKEN,
    SYSTEM_SP_TOKEN,
    THINKING_END_TOKEN,
    THINKING_START_TOKEN,
    USER_SP_TOKEN,
    AssistantMessage,
    BytesImageSource,
    CalcResizeError,
    ChatCompletionChunk,
    ChatCompletionChunkGenerator,
    ChatCompletionRequest,
    ChatCompletionResponse,
    Conversation,
    ConversationRequest,
    ConversionError,
    ConversionOptions,
    DataUrlImageSource,
    DeepseekV41Encoding,
    DeepseekV4Encoding,
    ImageError,
    ImageInfo,
    ImageQuota,
    ImageSource,
    InferenceChunk,
    InferenceFinishReason,
    InferenceOptions,
    LatestReminderMessage,
    Message,
    MessagesChunkGenerator,
    MessagesRequest,
    MessagesResponse,
    MessagesStreamEvent,
    MultiModalData,
    ParsingOptions,
    PreprocessOptions,
    PromptUsage,
    ReasoningStage,
    RenderedPrompt,
    ResponsesChunkGenerator,
    ResponsesRequest,
    ResponsesResponse,
    ResponsesStreamEvent,
    StreamProcessor,
    SystemMessage,
    Tokenizer,
    ToolCall,
    ToolDefinition,
    ToolMessage,
    UrlImageSource,
    UserMessage,
    WebSearchBehavior,
    __version__,
)

__all__ = [
    "ASSISTANT_SP_TOKEN",
    "BOS_TOKEN",
    "DSML_SP_TOKEN",
    "EOS_TOKEN",
    "IMAGE_SPECIAL_TOKEN",
    "IMAGE_SPECIAL_TOKEN_ID",
    "LATEST_REMINDER_SP_TOKEN",
    "SYSTEM_SP_TOKEN",
    "THINKING_END_TOKEN",
    "THINKING_START_TOKEN",
    "USER_SP_TOKEN",
    "AssistantMessage",
    "BytesImageSource",
    "CalcResizeError",
    "ChatCompletionChunk",
    "ChatCompletionChunkGenerator",
    "ChatCompletionRequest",
    "ChatCompletionResponse",
    "Conversation",
    "ConversationRequest",
    "ConversionError",
    "ConversionOptions",
    "DataUrlImageSource",
    "DeepseekV41Encoding",
    "DeepseekV4Encoding",
    "ImageError",
    "ImageInfo",
    "ImageQuota",
    "ImageSource",
    "InferenceChunk",
    "InferenceFinishReason",
    "InferenceOptions",
    "LatestReminderMessage",
    "Message",
    "MessagesChunkGenerator",
    "MessagesRequest",
    "MessagesResponse",
    "MessagesStreamEvent",
    "MultiModalData",
    "ParsingOptions",
    "PreprocessOptions",
    "PromptUsage",
    "ReasoningStage",
    "RenderedPrompt",
    "ResponsesChunkGenerator",
    "ResponsesRequest",
    "ResponsesResponse",
    "ResponsesStreamEvent",
    "StreamProcessor",
    "SystemMessage",
    "Tokenizer",
    "ToolCall",
    "ToolDefinition",
    "ToolMessage",
    "UrlImageSource",
    "UserMessage",
    "WebSearchBehavior",
    "__version__",
]

# Image fetching (reqwest) and OpenCV preprocessing are only present when the
# extension is built with the `image` feature (on by default). A render-only
# build (`--no-default-features`, for hosts without OpenCV/libclang) omits them,
# so import them best-effort — the package still loads for prompt rendering,
# token encoding, and response accumulation. `HAS_IMAGE_BINDINGS` reports which.
try:
    from ._native import (  # noqa: F401
        ImageResolver,
        OpenCvImagePreprocessor,
        ReqwestImageFetcher,
    )
except ImportError:
    HAS_IMAGE_BINDINGS = False
else:
    HAS_IMAGE_BINDINGS = True
    __all__ += ["ImageResolver", "OpenCvImagePreprocessor", "ReqwestImageFetcher"]

__all__ += ["HAS_IMAGE_BINDINGS"]
